global:
  scrape_interval: 10s
scrape_configs:
  - job_name: "spring-boot"
    metrics_path: /actuator/prometheus #endpoint
    static_configs:
      - targets:
          - "user-org.main.service:8080"
          - "task-org.main.service:8081"
          - "notification-org.main.service:8082"